# Generated by Django 2.0.1 on 2018-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BU', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('passWord', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=20)),
                ('BU', models.CharField(max_length=20)),
                ('audition1', models.TextField()),
                ('scale1', models.FloatField()),
                ('audition2', models.TextField()),
                ('scale2', models.FloatField()),
                ('audition3', models.TextField()),
                ('scale3', models.FloatField()),
                ('applyStatus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BUInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BU', models.CharField(max_length=20)),
                ('stage', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BU', models.CharField(max_length=20)),
                ('queue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SortMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BU', models.CharField(max_length=20)),
                ('messageType', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('other1', models.TextField()),
                ('other2', models.TextField()),
                ('other3', models.TextField()),
                ('other4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stu_id', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('tel', models.CharField(max_length=20)),
                ('QQ', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('academy', models.CharField(max_length=40)),
                ('isAdjust', models.CharField(max_length=1)),
                ('asp', models.CharField(max_length=40)),
                ('resume', models.TextField()),
                ('characterStage', models.CharField(max_length=20)),
                ('character', models.TextField()),
            ],
        ),
    ]
